Fixed the inconsistency issue in QFT(chapter 3.5)
qiskit-community/qiskit-textbook pull request #1058
Opened 2021-05-01 17:39 UTC by singhmeet11

The issue resolved is given in #970 

[3.5] Fixed the inconsistency in QFT chapter's

# Changes made
 The main aim was to eradicate the confusion between the |x> in section 1 and |x> in section 4. I have made the following changes:

1. |x> was not defined clearly, I defined a |X>(so that people don't get confused again) , I also changed the respective index from i to j (for X) and from i to k(for Y). 
2.  The mapping from |x> to |y> (which seemed confusing to me, because it nowhere mentions that we are talking about the whole vector or just one element), I used |j> and |k> for making this clearer .
3. The last change was in the U_{QFT} operator where I changed |x> and |y> to |j> and |k>.

No changes have been made anywhere except section 1. 

 

# Justification

1. This resolves the issue of intermixing of notations in section 1 and section 4. As there is a clear distinction between |X> and |x>.
2. Further replacing x and y by j and k in the powers of e, at a few places makes it easier to interpret the equations.
3. The overall linear algebra fits much better

2021-05-01 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-textbook?pullRequest=1058) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-textbook?pullRequest=1058) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-textbook?pullRequest=1058) it.</sub>

2021-05-12 14:30 UTC, divshacker requested changes
Hey @singhmeet11  you have just added two extra files which are not required. You have to just edit the quantum-fourier-transform.ipynb file and just make a PR which you have done already. but you need to delete these extra files you have added in your branch

2021-05-12 20:36 UTC, singhmeet11 commented
@divshacker thanks for helping me out. Does this look good ?? 
And sorry if its still wrong a little new to all this

2021-05-12 21:04 UTC, divshacker submitted a review, later dismissed
Now it's looks good.

2021-05-14 12:49 UTC, frankharkins requested changes
Thanks for having a go at this! I've suggested some changes:
- I think the `\\vert x_0  x_1  ...  x_{N-1}\\rangle` is maybe misleading as we generally use the label of a ket to refer to it's computational basis state, whereas here it seems `x_i` is the amplitude of the ith computational basis state.
- There are a few places I think the letters don't match up, I've suggested changes that I think makes the equations look right.

these equations are very dense though so it's possible I'm mistaken. Let me know what you think. 

Thanks!

2021-05-14 12:49 UTC, frankharkins commented on content/ch-algorithms/quantum-fourier-transform.ipynb
> +    "Similarly, the quantum Fourier transform acts on a quantum state $\\vert X\\rangle =\\vert x_0  x_1  ...  x_{N-1}\\rangle= \\sum_{i=0}^{N-1} x_j \\vert j \\rangle$ and maps it to the quantum sta
```suggestion
    "Similarly, the quantum Fourier transform acts on a quantum state $\\vert X\\rangle = \\sum_{j=0}^{N-1} x_j \\vert j \\rangle$ and maps it to the quantum state $\\vert Y\\rangle = \\sum_{k=0}^{N-1} y_k \\vert k \\rangle$ according to the formula\n",
```

2021-05-14 12:49 UTC, frankharkins commented on content/ch-algorithms/quantum-fourier-transform.ipynb
> +    "$$\\vert j \\rangle \\mapsto \\frac{1}{\\sqrt{N}}\\sum_{y=0}^{N-1}\\omega_N^{jk} \\vert k \\rangle$$\n",
```suggestion
    "$$\\vert j \\rangle \\mapsto \\frac{1}{\\sqrt{N}}\\sum_{k=0}^{N-1}\\omega_N^{jk} \\vert k \\rangle$$\n",
```

2021-05-17 15:25 UTC, frankharkins commented on content/ch-algorithms/quantum-fourier-transform.ipynb
> +    "Similarly, the quantum Fourier transform acts on a quantum state $\\vert X\\rangle =\\vert x_0  x_1  ...  x_{N-1}\\rangle= \\sum_{i=0}^{N-1} x_j \\vert j \\rangle$ and maps it to the quantum sta
```suggestion
    "Similarly, the quantum Fourier transform acts on a quantum state $\\vert X\\rangle = \\sum_{j=0}^{N-1} x_j \\vert j \\rangle$ and maps it to the quantum state $\\vert Y\\rangle = \\sum_{k=0}^{N-1} y_k \\vert k \\rangle$ according to the formula\n",
```

2021-05-17 17:34 UTC, frankharkins approved these changes
Thanks!

2021-05-17 18:29 UTC, merged