Update version info representation
qiskit-community/qiskit-textbook pull request #1134
Opened 2021-06-01 11:08 UTC by divshacker

# Changes made

Changed the last cell to represent the Version table in a better way. More  Details can be found in #1121 
# Justification

I changed the last cell to make it work.

2021-06-01 15:09 UTC, frankharkins requested changes
Looks like something funky going on with the image files. I'm not sure what's causing it but maybe try checking out these images from the master branch and committing again?

2021-06-01 15:19 UTC, divshacker commented on content/ch-algorithms/quantum-counting.ipynb
> +    "import qiskit.tools.jupyter\n",
Done! Thanks

2021-06-02 08:10 UTC, frankharkins approved these changes
Looks good, thanks!

2021-06-02 08:17 UTC, frankharkins requested changes

2021-06-02 08:17 UTC, frankharkins commented on content/ch-states/representing-qubit-states.ipynb
>  {
This could be the culprit here

2021-06-02 08:18 UTC, divshacker commented on content/ch-states/representing-qubit-states.ipynb
>  {
Yes I was thinking same

2021-06-02 09:49 UTC, frankharkins approved these changes
Thank you!

2021-06-02 09:49 UTC, merged