Update reprensentating -qubit-state.ipynb(easy qubit state representation)
qiskit-community/qiskit-textbook pull request #1236
Opened 2021-07-26 07:30 UTC by rajat709

here i have added line [3275-3278]
for visual representation of qubit it's give clear state of qubit and show how different gate acts on qubit state,
and also difines all gates in easy way!

# Changes made

# Justification

2021-07-26 07:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-textbook?pullRequest=1236) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-textbook?pullRequest=1236) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-textbook?pullRequest=1236) it.</sub>

2021-07-26 13:15 UTC, frankharkins requested changes
Happy to link to this demo, but think the wording needs changing a bit.

2021-07-26 13:15 UTC, frankharkins commented on content/ch-states/representing-qubit-states.ipynb
> +    "(For custom visual representation of qubit state [click here](https://javafxpert.github.io/grok-bloch/).\n"
```suggestion
    "You can also try [this interactive Bloch sphere demo](https://javafxpert.github.io/grok-bloch/).\n"
```

2021-07-26 13:15 UTC, frankharkins commented on content/ch-states/representing-qubit-states.ipynb
> +    "(or)\n",
```suggestion
```

2021-07-26 13:35 UTC, rajat709 commented
Sure sir, you rectify it!

On Mon, Jul 26, 2021, 6:45 PM Frank Harkins ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Happy to link to this demo, but think the wording needs changing a bit.
> ------------------------------
>
> In content/ch-states/representing-qubit-states.ipynb
> <https://github.com/qiskit-community/qiskit-textbook/pull/1236#discussion_r676591266>
> :
>
> > @@ -3271,7 +3271,11 @@
>
>      "\n",
>
>      "Below we have plotted a qubit in the state $|{+}\\rangle$. In this case, $\\theta = \\pi/2$ and $\\phi = 0$.\n",
>
>      "\n",
>
> -    "(Qiskit has a function to plot a bloch sphere, `plot_bloch_vector()`, but at the time of writing it only takes cartesian coordinates. We have included a function that does the conversion automatically).\n"
>
> +    "(Qiskit has a function to plot a bloch sphere, `plot_bloch_vector()`, but at the time of writing it only takes cartesian coordinates. We have included a function that does the conversion automatically).\n",
>
> +    "\n",
>
> +    "(or)\n",
>
> +    "\n",
>
> +    "(For custom visual representation of qubit state [click here](https://javafxpert.github.io/grok-bloch/).\n"
>
>
> ⬇️ Suggested change
>
> -    "(For custom visual representation of qubit state [click here](https://javafxpert.github.io/grok-bloch/).\n"
>
> +    "You can also try [this interactive Bloch sphere demo](https://javafxpert.github.io/grok-bloch/).\n"
>
>
> ------------------------------
>
> In content/ch-states/representing-qubit-states.ipynb
> <https://github.com/qiskit-community/qiskit-textbook/pull/1236#discussion_r676592132>
> :
>
> > @@ -3271,7 +3271,11 @@
>
>      "\n",
>
>      "Below we have plotted a qubit in the state $|{+}\\rangle$. In this case, $\\theta = \\pi/2$ and $\\phi = 0$.\n",
>
>      "\n",
>
> -    "(Qiskit has a function to plot a bloch sphere, `plot_bloch_vector()`, but at the time of writing it only takes cartesian coordinates. We have included a function that does the conversion automatically).\n"
>
> +    "(Qiskit has a function to plot a bloch sphere, `plot_bloch_vector()`, but at the time of writing it only takes cartesian coordinates. We have included a function that does the conversion automatically).\n",
>
> +    "\n",
>
> +    "(or)\n",
>
>
> ⬇️ Suggested change
>
> -    "(or)\n",
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/qiskit-community/qiskit-textbook/pull/1236#pullrequestreview-714827466>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3JMAPJCLGJX7JYA3LXK53TZVNXZANCNFSM5A7QYY2Q>
> .
>

2021-07-28 10:05 UTC, frankharkins approved these changes
Thanks!

2021-07-28 10:05 UTC, merged