[1.4, 8.1] Issue 719: enhanced explanation for measuring in different basis
qiskit-community/qiskit-textbook pull request #1323
Opened 2021-11-06 13:45 UTC by dhruvbhq

# Changes made

To resolve #719.

- In appendix on linear algebra (8.1), clearly stated that the eigenvectors of Hermitian and unitary operators form a basis for the underlying vector space.
- In chapter 1.4, single qubit states, added a note that since X and Y are Hermitian/unitary, their eigenvectors indeed form a basis due to the above property. (Referred it to the appendix)
- In chapter 1.4, single qubit states, added a short paragraph to show that state expressed in X-basis is obtained from state expressed in Z-basis by multiplying with Hadamard matrix.

# Justification

In the issue #719, it was discussed that the explanation of measuring in different bases could be improved and some gaps in explanation could be filled. First, it required clarifying the above property of eigenvectors of Hermitian and unitary operators. In this PR, this has been handled by adding it in the appendix dedicated to linear algebra. For enhancing the explanation for 1.4, the claim that eigenvectors of X and Y are a basis for the vector space needed to be supported by this property. A short note has been added for that. Further, in 1.4, a paragraph has been added to motivate why the Hadamard matrix translates from Z-basis measurement to one in the X-basis (as it was proposed in the issue).

2021-11-08 10:21 UTC, frankharkins requested changes
Looks good, thank! Just one small suggestion.

2021-11-08 10:21 UTC, frankharkins commented on content/ch-states/single-qubit-gates.ipynb
> +    "We leave it as an exercise to calculate these. There are in fact an infinite number of bases; to form one, we simply need two orthogonal vectors. Recall, from the appendix on linear algebra, tha
```suggestion
    "We leave it as an exercise to calculate these. There are in fact an infinite number of bases; to form one, we simply need two orthogonal vectors. The eigenvectors of both Hermitian and unitary matrices form a basis for the vector space. Due to this property, we can be sure that the eigenstates of the X-gate and the Y-gate indeed form a basis for 1-qubit states (read more about this in the [linear algebra page](https://qiskit.org/textbook/ch-appendix/linear_algebra.html#Matrices-and-Matrix-Operations) in the appendix)\n",
```

We don't require people read the LA page beforehand so I think better to include it as a reference.

2021-11-10 09:38 UTC, frankharkins approved these changes
Thank you!

2021-11-10 09:38 UTC, merged

2021-11-10 22:24 UTC, dhruvbhq commented
Thank you @frankharkins ! It was great to work on this issue.