[4.1.2] Removed Qiskit Aqua references
qiskit-community/qiskit-textbook pull request #1347
Opened 2021-12-19 11:39 UTC by Ryand1234

fixes #1331 
# Changes made

removed Qiskit aqua references
# Justification

removed qiskit-aqua references from the code and related text which is being deprecated.

2021-12-23 16:44 UTC, divshacker commented on content/ch-applications/vqe-molecules.ipynb
> +   "execution_count": 9,
Can you change these execution counts by rerunning all the cells from starting?
Also, you haven't executed some of the last cells. Please rerun them too.

2021-12-23 18:34 UTC, frankharkins requested changes
Thank you so much for taking a look at this. While running your notebook I got this error:
```
AttributeError: type object 'Z2Symmetries' has no attribute 'two_qubit_reduction'
```

In this 8th code cell. We need the entire notebook to run correctly before we can merge.

2021-12-24 05:32 UTC, Ryand1234 commented
@frankharkins I am not getting this error, Its working fine for me. But I am getting 

`QiskitChemistryError: 'PySCF is not installed. See https://sunqm.github.io/pyscf/install.html'` 

error. I tried installing PySCF but its not installing.

2021-12-24 06:27 UTC, divshacker commented
> @frankharkins I am not getting this error, Its working fine for me. But I am getting
> 
> `QiskitChemistryError: 'PySCF is not installed. See https://sunqm.github.io/pyscf/install.html'`
> 
> error. I tried installing PySCF but its not installing.

Hey, you are not facing any errors because you haven't updated the Qiskit version. 
Can you show your version info?

2021-12-24 06:44 UTC, divshacker commented
Here is mine, Verify if it matches with your system too by running this. 
``` 
import qiskit.tools.jupyter
%qiskit_version_table
```

<h3 style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: bold; line-height: 1; color: rgb(0, 0, 0); margin: 0.777em 0px 0px; font-size: 18.004px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Version Information</h3>

Qiskit Software | Version
-- | --
qiskit-terra | 0.19.1
qiskit-aer | 0.10.1
qiskit-ignis | 0.7.0
qiskit-ibmq-provider | 0.18.3
qiskit-aqua | 0.9.5
qiskit | 0.34.0
qiskit-nature | 0.3.0
qiskit-finance | 0.3.0
qiskit-optimization | 0.3.0
qiskit-machine-learning | 0.3.0

2023-05-30 12:31 UTC, closed without merging

2023-05-30 12:31 UTC, frankharkins commented
Thanks for your contribution. I'm closing this pull request as this repository is no longer used and is being archived. You can find the latest version of the Qiskit Textbook online at <https://qiskit.org/learn/>, and the new content repository at [Qiskit/textbook](https://github.com/Qiskit/textbook). Please feel free to re-open this pull request there if it's still relevant.