Bugs
qiskit-community/qiskit-textbook pull request #1480
Opened 2022-09-02 16:22 UTC by divshacker

# Changes made

I have updated the tutorial with updated packages and removing deprecated ignis from the tutorials. 

# Justification

All the details can be found in issues ranging from #1470 to #1479

2022-09-02 16:26 UTC, divshacker commented
This PR fixes #1470 #1471 #1472 till now. 
Thanks @1ucian0 for reporting these issues.

2022-09-02 16:46 UTC, divshacker commented
fixed #1474

2022-09-02 16:56 UTC, divshacker commented
fixed #1475

2022-09-04 13:06 UTC, 1ucian0 commented
I think the `Fixes` notation only works on the first post. Try editing it.

2022-09-05 13:30 UTC, frankharkins requested changes
Thanks! 

I've left a couple of comments about compatibility issues. To avoid disrupting people teaching with this version of the textbook, we're avoiding making large changes. Corrections / small substitutions are fine, but I'm hesitant to make large content changes. Despite deprecation, Ignis does still work and people can still install it with the qiskit version at the bottom of the page to get things working.

2022-09-05 13:30 UTC, frankharkins commented on content/ch-quantum-hardware/measuring-quantum-volume.ipynb
> +    "import qiskit_experiments.library.quantum_volume as qv"
```suggestion
    "import qiskit.ignis.verification.quantum_volume as qv"
```

Unfortunately this isn't a drop-in replacement as the page relies too heavily on old ignis functionality. I think we leave this as-is; the new textbook will soon have an updated version that uses `qiskit_experiments` (see commit https://github.com/Qiskit/platypus/pull/1505/commits/846a7c5bf7304cf06432577d044a34f7bca9a5bd of PR https://github.com/Qiskit/platypus/pull/1505).

2022-09-05 13:30 UTC, frankharkins commented on content/ch-quantum-hardware/randomized-benchmarking.ipynb
> +    "import qiskit_experiments.library.randomized_benchmarking as rb\n",
Same problem here; when running I get 
```
AttributeError: module 'qiskit_experiments.library.randomized_benchmarking' has no attribute 'randomized_benchmarking_seq'
```

If it only takes a couple of lines to get it working then we can do that, for any larger changes we should leave it using ignis and do a re-write in the new textbook.

2023-05-30 12:31 UTC, closed without merging