[4.1.3] Fixed typo in Appendix 2.1
qiskit-community/qiskit-textbook pull request #1491
Opened 2022-10-06 00:43 UTC by giorgosgiapis

# Changes made

Changed $(i,k)\in E$ to $(i,j)\in E$.

# Justification

$k$ did not appear anywhere in the above text.

2022-10-06 00:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/qiskit-community/qiskit-textbook?pullRequest=1491) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/qiskit-community/qiskit-textbook?pullRequest=1491) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/qiskit-community/qiskit-textbook?pullRequest=1491) it.</sub>

2022-10-17 14:59 UTC, frankharkins commented
@giorgosgiapis looks like you've unintentionally made ~4000 lines of changes. Can you please reset any changes other than the typo correction? If you're not sure how to do that, see [this comment](https://github.com/qiskit-community/qiskit-textbook/pull/1498#issuecomment-1280901096) for instructions on a PR with a similar problem.

2022-10-17 14:59 UTC, frankharkins requested changes
Setting status to 'requesting changes'; see comment above.

2022-10-17 17:42 UTC, giorgosgiapis commented
I have opened a new PR as per the instructions in the referenced PR. See [here](https://github.com/qiskit-community/qiskit-textbook/pull/1502).

2022-10-17 17:42 UTC, closed without merging